[tool.poetry]
name = "phd-clouds"
version = "0.1.0"
description = ""
authors = ["Matheus Tolentino da Silva <matolentino.silva@gmail.com>"]
readme = "README.md"
packages = [{include = "phd_clouds"}]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "<1.25"
matplotlib = "*"
netCDF4 = "*"
pandas = "*"
scipy = "*"
xarray = "*"
dask = "*"
seaborn = "*"
colorcet = "*"
ipython = "^7.0"
ipykernel = "^6.25.1"
bottleneck = "^1.3.7"
distributed = "^2023.9.1"
vaex = "^4.17.0"
scikit-learn = "^1.3.1"
cloudnetpy-qc = "^1.14.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
